pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'Java17'
    }

    environment {
        COMPOSE_FILE = 'docker-compose.yml'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ahmed-zain10/petclinic.git',
                    credentialsId: 'github-token'
            }
        }

        stage('Build JAR') {
            steps {
                dir('spring-petclinic') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Start with Docker Compose') {
            steps {
                dir('spring-petclinic') {
                    sh 'docker compose up -d'
                }
            }
        }
        stage('Verify') {
            steps {
                sh '''
                for i in $(seq 1 30); do
                  if curl -f http://localhost:7070; then
                    echo "App is up!"
                    exit 0
                  fi
                  echo "App not ready yet... retrying in 150s"
                  sleep 150
                done
                echo "App did not start!"
                exit 1
                '''
            }
        }

    }

    post {
        always {
            dir('spring-petclinic') {
                sh 'docker compose down || true'
            }
        }
    }
}
